### ISSUE TITLE
Add Heroku PR review apps

### ISSUE THREAD

**Issue by maxneuvians** [cds-snc/gc-simple-dictionary#7]
Consider adding Heroku PR review apps to prevent https://github.com/cds-snc/gc-simple-dictionary/pull/5 - there does not seem to be an easy way to do CI, so a manual test is probably required. You might need to pull in https://github.com/heroku/heroku-buildpack-static if Heroku does not detect the static site.

**Comment by wmoussa-cds** [comment]
Done https://github.com/cds-snc/gc-simple-dictionary/pull/11 - I used the index.php hack to make Heroku believe it's a dynamic app.

**Comment by wmoussa-cds** [comment]
Something worth remembering with automatic creation, Heroku creates a review app as soon as a pull request is opened on your app’s connected GitHub repo. For security and billing reasons, Heroku does not automatically create review apps for pull requests to public repos that are sent from forks. You can still create review apps for these pull requests manually.

**Comment by dj2** [comment]
To my continual, fork loving, sadness.

**Comment by wmoussa-cds** [comment]
Heroku is not used anymore. So preview is probably broken.
